[tool.poetry]
name = "OntoLearner"
version = "1.1.0"
description = "OntoLearner: A Modular Python Library for Ontology Learning with LLMs."
authors = ["Hamed Babaei Giglou <hamedbabaeigiglou@gmail.com>", "Andrei C. Aioanei <andrei.c.aioanei@gmail.com>"]
license = "MIT License"
readme = "README.md"
homepage = "https://ontolearner.readthedocs.io/"
repository = "https://github.com/sciknoworg/OntoLearner/"
include = ["images/logo.png"]

[tool.poetry.dependencies]
python = ">=3.10,<3.13.0"
rdflib ="7.1.1"
networkx ="3.2.1"
seaborn="0.13.2"
numpy="2.2.4"
pandas="2.2.3"
matplotlib="3.10.0"
tqdm="4.67.1"
pydantic="2.11.3"
pathlib="1.0.1"
dspy="2.6.14"
python-dotenv="1.1.0"
huggingface-hub=">=0.30.0"
transformers="4.51.3"
torch="2.7.0"
sentence-transformers="4.1.0"
scikit-learn="1.6.1"

[tool.poetry.dev-dependencies]
ruff = "*"
pre-commit = "*"
setuptools = "*"
wheel = "*"
twine = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
